apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  hostNetwork: true
  initContainers:
    - name: configurator-init
      image: povilasv/configurator:arm-0.1.0
      args:
        - "-config=/etc/app/app.json"
        - "-onetime"
      volumeMounts:
        - name: config
          mountPath: /etc/app
  containers:
    - name: app
      image: povilasv/app:arm-0.2.0
      args:
        - "-config=/etc/app/app.json"
      resources:
        limits:
          cpu: "100m"
          memory: "50Mi"
      volumeMounts:
        - name: config
          mountPath: /etc/app
    - name: configurator
      image: povilasv/configurator:arm-0.1.0
      args:
        - "-config=/etc/app/app.json"
      volumeMounts:
        - name: config
          mountPath: /etc/app
  volumes:
    - name: config
      emptyDir: {}
